### ISSUE TITLE
Create trivia minigame

### ISSUE THREAD

**Issue by Strike2610** [AlkmaarMania/AlkmaarMania#173]

**Comment by mona12rst** [comment]
implement a trivia game to ask questions from the user and reward the user based on the answers given. 5 hours. @Strike2610 
implement a small hardcoded database of questions and answers to choose from. 3hours. @Strike2610

**Comment by mona12rst** [comment]
08//06/2022
No changes. not implemented.

**Comment by mona12rst** [comment]
will be completely finished single-player, by Tuesday night, maximum Wednesday morning.
