### ISSUE TITLE
Add sound effects for different actions

### ISSUE THREAD

**Issue by abbydiode** [AlkmaarMania/AlkmaarMania#373]
- [ ] Building tapped sound effect
- [ ] Upgrade menu closed sound effect
- [ ] Light bulb upgraded sound effect
- [ ] Heating upgraded sound effect
- [ ] Solar panel installed sound effect
- [ ] Solar panel upgraded sound effect
- [ ] Objective tap sound effect
- [ ] Objective completed sound effect
- [ ] Add Bike Bell

**Comment by mona12rst** [comment]
08/06/2022
No change. not implemented.
