### ISSUE TITLE
Add complete localization for everything

### ISSUE THREAD

**Issue by abbydiode** [AlkmaarMania/AlkmaarMania#404]
And also a default way for the application to switch locales
Add cheat button to switch language

**Comment by abbydiode** [comment]
> 08/06/2022 No change. not working.

Localization is working, but not everything has been localized yet, that's actively being worked on

**Comment by mona12rst** [comment]
> > 08/06/2022 No change. not working.
> 
> Localization is working, but not everything has been localized yet, that's actively being worked on

![image](https://user-images.githubusercontent.com/64336157/172623969-7d887aef-3e2a-4ce4-b273-1ae9b7105a08.png)


there is nothing being translated in the game. there is a button on top to change to NL, but nothing gets translated.

**Comment by abbydiode** [comment]
> > > 08/06/2022 No change. not working.
> > 
> > 
> > Localization is working, but not everything has been localized yet, that's actively being worked on
> 
> ![image](https://user-images.githubusercontent.com/64336157/172623969-7d887aef-3e2a-4ce4-b273-1ae9b7105a08.png)
> 
> there is nothing being translated in the game. there is a button on top to change to NL, but nothing gets translated.

Strange because these were definitely implemented before, perhaps we should figure out where the implementation got removed?

![image](https://user-images.githubusercontent.com/16174954/172624425-661ccf88-e0d1-4700-9884-e61decda8fe5.png)

**Comment by abbydiode** [comment]
> > > > > 08/06/2022 No change. not working.
> > > > 
> > > > 
> > > > Localization is working, but not everything has been localized yet, that's actively being worked on
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/64336157/172623969-7d887aef-3e2a-4ce4-b273-1ae9b7105a08.png)
> > > there is nothing being translated in the game. there is a button on top to change to NL, but nothing gets translated.
> > 
> > 
> > Strange because these were definitely implemented before, perhaps we should figure out where the implementation got removed?
> > ![image](https://user-images.githubusercontent.com/16174954/172624425-661ccf88-e0d1-4700-9884-e61decda8fe5.png)
> 
> that could be an obvious answer (as far as I know). a lot has changed since last localization was implemented. we changed the whole design of menus and classes have also changed quite some according to Eef's requests. so it could be there. but I might be wrong, I didnt implement anything about localization so my knowledge can very well be wrong.

![image](https://user-images.githubusercontent.com/16174954/172625920-9baca10a-687a-4b29-94dd-9c7a1de1cdd1.png)

It used to be implemented as such, however I'm unsure why this got lost. Ultimately, this just has to be re-implemented, but it's a tedious task to do that for all strings in the game so that will take some time.

**Comment by mona12rst** [comment]
Abby has left the team and this task was not implemented in any way. all the previous implementations were completely non functional due to changes of the game and no changes were made to the localization, making it completely non functional. this task has to be picked up by Zarmina from scratch.

**Comment by Zarmina** [comment]
absoloutely no localization had been implemented previously, all the keys shown in the pictures above were only texts and had no value and were not implemented by any means in the app, all localization had to be fully implemented from scratch, it is almost finished now.
